server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    password: ${DATABASE_USERNAME:parcel}
    username: ${DATABASE_PASSWORD:parcel}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/parcel_delivery}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: parcel-delivery-events
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all

parcel:
  kafka:
    topic: parcel-events