/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":infrastructure"))
}

application {
    mainClass = "org.example.AppKt"
}
